language: php
dist: xenial

services:
   - mysql

cache:
  directories:
    - .cache
    - vendor
    # Cache directory for older Composer versions.
    - $HOME/.composer/cache/files
    # Cache directory for more recent Composer versions.
    - $HOME/.cache/composer/files

branches:
  only:
    - master
    - trunk
    - /^release\/\d+\.\d+(\.\d+)?(-\S*)?$/
    - /^hotfix\/\d+\.\d+(\.\d+)?(-\S*)?$/
    - /^feature\/*/
    # Also build tags like 1.1.1 or 1.1 for deployment.
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/

jobs:
  fast_finish: true
  include:
    - php: 7.3
      env: WP_VERSION=master PHPUNIT=1
    - php: 7.2
      env: WP_VERSION=5.4 WP_MULTISITE=1 PHPCS=1 SECURITY=1 COVERAGE=1
    - php: 5.6
      env: WP_VERSION=5.3 WP_MULTISITE=1 PHPLINT=1 PHPUNIT=1
      # Use 'trusty' to test against MySQL 5.6, 'xenial' contains 5.7 by default.
      dist: trusty
    - php: 7.4
      env: WP_VERSION=5.4 PHPLINT=1 PHPUNIT=1
    - php: "nightly"
      env:  PHPLINT=1
    - stage: deploy-to-github-dist
      env: WP_VERSION=latest
      if: tag IS present
      before_install:
        - openssl aes-256-cbc -K $encrypted_b489f7a38f66_key -iv $encrypted_b489f7a38f66_iv -in ./deploy_keys/wpseo_news_deploy.enc -out ./deploy_keys/wpseo_news_deploy -d
        - chmod 600 ./deploy_keys/wpseo_news_deploy
        - eval $(ssh-agent -s)
        - ssh-add ./deploy_keys/wpseo_news_deploy
      before_deploy:
        - nvm install node
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH=$HOME/.yarn/bin:$PATH
        - yarn global add grunt-cli
        - yarn install
        - grunt set-version -new-version=$TRAVIS_TAG
        - grunt update-version
        - grunt artifact
      # If the commit was tagged, create an artifact and push it to the distribution github
      deploy:
        skip_cleanup: true
        provider: script
        script: bash scripts/deploy_to_dist.sh $TRAVIS_TAG wpseo-news
        on:
          tags: true
          repo: $TRAVIS_REPO_SLUG
          all_branches: true
  allow_failures:
    # Allow failures for unstable builds.
    - php: "nightly"
    - php: 7.3
      env: WP_VERSION=master PHPUNIT=1

before_install:
- if [[ "$COVERAGE" != "1" ]]; then phpenv config-rm xdebug.ini || echo 'No xdebug config.'; fi
- export SECURITYCHECK_DIR=/tmp/security-checker

install:
- |
  if [[ "$PHPCS" == "1" || "$PHPUNIT" == "1" || "$COVERAGE" == "1" ]]; then
    composer install --no-interaction
  elif [[ "$TRAVIS_BUILD_STAGE_NAME" == "deploy-to-github-dist" ]]; then
    composer install --no-dev --no-interaction
  fi
- |
  if [[ "$COVERAGE" == "1" ]]; then
    # Install phpcov so we can combine the coverage results of unit and integration tests.
    composer require phpunit/phpcov ^3.1
  fi
- if [[ "$SECURITY" == "1" ]]; then wget -P $SECURITYCHECK_DIR https://get.sensiolabs.org/security-checker.phar && chmod +x $SECURITYCHECK_DIR/security-checker.phar;fi

before_script:
# Careful: The HTTPS version of the following URL is different, therefore we need to use HTTP.
- |
  if [[ "$WP_VERSION" == "latest" ]]; then
    curl -s http://api.wordpress.org/core/version-check/1.7/ > /tmp/wp-latest.json
    WP_VERSION=$(grep -o '"version":"[^"]*' /tmp/wp-latest.json | sed 's/"version":"//')
  fi
- PLUGIN_SLUG=$(basename $(pwd))
- export WP_DEVELOP_DIR=/tmp/wordpress/
- export -f travis_fold
- export -f travis_time_start
- export -f travis_time_finish

- |
  if [[ "$COVERAGE" == "1" ]]; then
    curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    chmod +x ./cc-test-reporter
    ./cc-test-reporter before-build
    mkdir -p /tmp/coverage
  fi

# Clone WordPress
#
- |
  if [[ "$PHPUNIT" == "1" || "$COVERAGE" == "1" ]]; then
    git clone --depth=1 --branch="$WP_VERSION" git://develop.git.wordpress.org/ /tmp/wordpress
  fi

# Clone WPSEO and its submodule
#
- |
  if [[ "$PHPUNIT" == "1" || "$COVERAGE" == "1" ]]; then
    git clone --depth=1 --branch="trunk" https://github.com/Yoast/wordpress-seo.git $WP_DEVELOP_DIR/src/wp-content/plugins/wordpress-seo
    cd /tmp/wordpress/src/wp-content/plugins/wordpress-seo
    composer install --no-dev --no-interaction --ignore-platform-reqs
    cd -
  fi

# Copy news seo to test dir
- |
  if [[ "$PHPUNIT" == "1" || "$COVERAGE" == "1" ]]; then
    cd ..
    cp -r "$PLUGIN_SLUG" "$WP_DEVELOP_DIR/src/wp-content/plugins/$PLUGIN_SLUG"
    cd /tmp/wordpress/
    cp wp-tests-config-sample.php wp-tests-config.php
    sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
    sed -i "s/yourusernamehere/travis/" wp-tests-config.php
    sed -i "s/yourpasswordhere//" wp-tests-config.php
    mysql -e "CREATE DATABASE wordpress_tests;" -uroot
    cd "$WP_DEVELOP_DIR/src/wp-content/plugins/$PLUGIN_SLUG"
    phpenv rehash
  fi

script:
# JavaScript checks
- |
  if [[ "$CHECKS" == "1" ]]; then
    travis_fold start "JavaScript.check" && travis_time_start
    npm install -g grunt-cli && npm install --no-optional && grunt check:js
    travis_time_finish && travis_fold end "JavaScript.check"
  fi
# PHP Linting
- |
  if [[ "$PHPLINT" == "1" ]]; then
    travis_fold start "PHP.check" && travis_time_start
    find -L . -path ./vendor -prune -o -path ./node_modules -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
    travis_time_finish && travis_fold end "PHP.check"
  fi
# PHP Code Style
- |
  if [[ "$PHPCS" == "1" ]]; then
    travis_fold start "PHP.code-style" && travis_time_start
    composer check-cs
    travis_time_finish && travis_fold end "PHP.code-style"
  fi
# PHP Integration Tests
- |
  if [[ "$PHPUNIT" == "1" ]]; then
    travis_fold start "PHP.integration-tests" && travis_time_start
    composer integration-test
    travis_time_finish && travis_fold end "PHP.integration-tests"
  fi
# PHP Unit Tests
- |
  if [[ "$PHPUNIT" == "1" ]]; then
    travis_fold start "PHP.tests" && travis_time_start
    composer test
    travis_time_finish && travis_fold end "PHP.tests"
  fi
# PHP Coverage
- |
  if [[ "$COVERAGE" == "1" ]]; then
    travis_fold start "PHP.coverage.part1" && travis_time_start
    composer integration-test -- --coverage-php /tmp/coverage/integration-tests.cov
    travis_time_finish && travis_fold end "PHP.coverage.part1"
  fi
- |
  if [[ "$COVERAGE" == "1" ]]; then
    travis_fold start "PHP.coverage.part2" && travis_time_start
    composer test -- --coverage-php /tmp/coverage/tests.cov
    travis_time_finish && travis_fold end "PHP.coverage.part2"
  fi
- if [[ $TRAVIS_PHP_VERSION == "5.6" || $TRAVIS_PHP_VERSION == "7.4" ]]; then composer validate --no-check-all; fi
# Check for known security vulnerabilities in the currently locked-in dependencies.
- if [[ "$SECURITY" == "1" ]]; then php $SECURITYCHECK_DIR/security-checker.phar -n security:check $(pwd)/composer.lock;fi

after_script:
- |
  if [[ "$COVERAGE" == "1" ]]; then
    ./vendor/bin/phpcov merge /tmp/coverage --clover build/logs/clover.xml
  fi
- if [[ "$COVERAGE" == "1" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
